version: '3.8'

services:
  wheatvoiceapp-service:
    image: paperapi:1.0
    container_name: wheatvoice-app
    ports:
      - "5001:5001"
    volumes:
      - ./app:/root/app
    networks:
      - app-network
    command:
      - python run_wheatvoice.py

  wheatvoicevue-service:
    image: papervue:1.0
    container_name: wheatvoice-vue
    ports:
      - "11120:8080"
    volumes:
      - ./web-vue:/root/web-vue
    networks:
      - app-network

  wheatvoicemysql-service:
    image: mysql:8.0.36
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=wheatvoice123456
      - MYSQL_DATABASE=wheatvoice
    volumes:
      - ./mysql/conf/my.cnf:/etc/mysql/my.cnf
      - ./mysql/data:/var/lib/mysql
      - ./app/conf/wheatvoice_init.sql:/docker-entrypoint-initdb.d/wheatvoice_init.sql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge